# Constants
kWorkAreaFile = '.ipbb_work.yml'
kProjAreaFile = '.ipbb_proj.yml'
kProjUserFile = '.ipbb_user.yml'
kRepoFile = '.ipbb_repo.yml'
kDeprecatesSetupFile = '.ipbb_setup.yml'
kSourceDir = 'src'
kProjDir = 'proj'
kTopDep = 'top'
kTopEntity = 'top'
